PROGRAMA ::= 'program' '(' 'id' ')' BLOQUE
BLOQUE ::= '{' (VARS* FUNCTION* ESTATUTO*)* '}'
VARS ::= TIPO 'id' ('=' EXP)? ';'
FUNCTION ::= TIPO 'id' '(' TIPO 'id' (',' TIPO 'id')* ')' BLOQUE
TIPO ::= ( 'int' | 'float' | 'char' | 'string' )?
ESTATUTO ::= (ASIGNACION | CONDICION | ESCRITURA | LECTURA | CICLO)
ASIGNACION ::= 'id' '=' EXPRESION ';'
CONDICION ::= 'if' '(' EXPRESION ')' BLOQUE ('else' BLOQUE)?
ESCRITURA ::= ('out' '(' (EXPRESION | 'string') ')' ';' | 'fout' '(' (EXPRESION | 'string') ',' 'cte file' ')' ';' )
LECTURA ::= ('in' '(' 'id' ')' ';' | 'fin' '(' 'id' ',' 'cte file' ')' ';' )
CICLO ::= (WHILE | FOR)?
WHILE ::= 'while' '(' EXPRESION ')' BLOQUE
FOR ::= 'for' '(' ASIGNACION ';' EXPRECION ';' ASIGNACION ')' BLOQUE
EXPRESION ::= EXP (( '>' | '<' | '<>' ) EXP )?
EXP ::= (TERMINO (('+' | '-')TERMINO)*)
TERMINO ::= (FACTOR  (('*' | '/')FACTOR)*)
FACTOR ::= ('(' EXPRESION ')' | ('+' | '-')? VAR_CTE)
VAR_CTE ::= ( 'ID' | 'cte int' | 'cte float' | 'cte char' | 'cte string' | 'cte file')?
